### ISSUE TITLE
Handle render dynamic theme style bootstrap

### ISSUE THREAD

**Issue by PhamMinhHaiAu-12035071** [pham-minh-hai-au-react-native/ReactstrapNativeWeb#6]

**Comment by PhamMinhHaiAu-12035071** [comment]
please checkout new branch RSNW#6 for handle this ticket

**Comment by phungvanquyet** [comment]
I can't push code to new branch  RSNW#6. Please check and authorization for me.

**Comment by PhamMinhHaiAu-12035071** [comment]
Ok, I have handled it, default create repository will mode read for all member I have changed to write mode repository. Now you can push code.
